### ISSUE TITLE
03-US / 03-Home / feature/home_screen

### ISSUE THREAD

**Issue by Hirnstromwelle** [Hirnstromwelle/userStories#1]
## Value Proposition

**As a** User

**I want** to see the landing page when i start the App.

**to be able to** that I am greeted with my name.

## Description

<img width="277" alt="Screenshot 2022-12-19 at 16 40 13" src="https://user-images.githubusercontent.com/63350892/208463584-b888b966-bec4-442e-a494-1430f63b7f83.png">

Scribble / design or text

## Acceptance Criteria

- [x] Greeting text
- [x] Staircase image display 
- [x] expand navigation bar

## Tasks

(for developers team)

- [x] add welcome components
- [x] add image file as svg 
- [x] add home in navigation map
- [x] branch feature/home_screen
- [x] home styles
- [x] testing

**Comment by Hirnstromwelle** [comment]
## Value Proposition

**As a** ...(user, Author, logged in User...)

**I need** ...(describe the goal)

**to be able to** ...(describe the reason)

## Description

Scribble / design or text

## Acceptance Criteria

- [ ] describe every scenario in detail
- [ ] e.g. All Inputs are required, show warning if empty.
- [ ] ...

## Tasks

(for developers team)

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] ...

**Comment by esrefbozkurt** [comment]
The US is very good. Good structure! 
At the beginning i would say "to be able to be greeted with my name".
And What do you mean with "navigation map"?
