### ISSUE TITLE
1-US / 06-Appointments / main_structure

### ISSUE THREAD

**Issue by Hirnstromwelle** [Hirnstromwelle/userStories#2]
## Value Proposition

**As a** user

**I want** to see my tasks

**to be able to** get an overview of which item is due next

## Description

![Screenshot 2022-12-13 at 10 10 11](https://user-images.githubusercontent.com/63350892/207275408-74c63618-f853-485f-b6f8-5752c0210906.png)

Scribble / design or text

## Acceptance Criteria

- [x] Page has a header with title
- [x] Page shows a list of tasks
- [x] tasks are displayed below each other
- [x] List can be scrolled down when there are many items

## Tasks

(for developers team)

- [x] Create a new project with next
- [x] work on a branch
- [x] create header components
- [x] create tasks components
- [x] add dummy data
- [x] add style Components
- [x] testing

**Comment by julialoeschel** [comment]
Coole erste Story! 

Aus dem Bild könntest du die obersten paar pixel, in denen die Telefondaten(Zeit und Netzt und so)  angezeigt werden, ruhig rausnehmen. 
Die gehören nicht zur Story. 

:octocat:

**Comment by Hirnstromwelle** [comment]
> Hi Alex, die zwei * vor und hinter Wörtern sind dafür da, dass der Teil des Textes dickgedruckt ist. Oben hast du die hintenstehenden * weggenommen, die könntest du der Schönheit halber wieder einbauen ;) Ich bin mir auch unsicher, ob dein Bild schon etwas zu detailliert ist, mit dem Styling und so, aber vielleicht ist das auch egal und nur ein Anhaltspunkt :)

Erledigt - super DANKE. : )
