### ISSUE TITLE
02-US / 06-Appointments 05-Add-New / feature/nav_bar_add_page

### ISSUE THREAD

**Issue by Hirnstromwelle** [Hirnstromwelle/userStories#4]
## Value Proposition

**As a** User 

**I need** to navigate in a other section

**to be able to** add new tasks

## Description

![Screenshot 2022-12-13 at 10 15 42](https://user-images.githubusercontent.com/63350892/207276669-c6292ece-0543-4e0e-943f-6effe5c3f211.png)

Scribble / design or text

## Acceptance Criteria

- [x] welcome text with picture 
- [x] new page to added new appointments
- [x] enter dates for cleaning week

## Tasks

(for developers team)

- [x] work on a branch
- [x] create header element with picture and welcome text
- [x] create navigation routing
- [x] the navigation should be flexibel component at the bottom of the page
- [x] on the click on the nav buttons changes the color and the URL
- [x] testing

**Comment by julialoeschel** [comment]
Hello, 
Auf der neuen Steite (Routing?, dann muss dan in Tasks auftauchen)  kannst du das Formular direkt darstellen. 
wenn du dann mal mehrere Fomulare hast, brauchst du noch so eine Zwischenseite, für jetzt reicht aber einfach das Formular. 

in den AC fehlt mir noch: Wo tauchen die Daten auf, wenn ich sie in mein Fomular eingegeben habe? 
Auf der ersten Seite vermutlich?  unten? oben? 

:octocat:

**Comment by flipkoehler** [comment]
Hey Alex, 
ich würde empfehlen, die Story vielleicht in zwei User Stories aufzuteilen. Sprich eine Story für die Navigation inkl. der Begrüßung des Nutzers und eine Story das Formular. Die Story wirkt recht groß. Aber das kannst du natürlich entscheiden :) 
vielleicht kannst du auch noch beschreiben was beim Navigationsklick passiert. Sprich: Die Farbe ändert sich, die URL ändert sich... 

Der Punkt was mit den Daten nach dem Absenden passiert müsste auch noch beschrieben werden. Also werden die Daten darunter angezeigt oder ein neuer Eintrag generiert?

**Comment by Hirnstromwelle** [comment]
> Hey Alex, ich würde empfehlen, die Story vielleicht in zwei User Stories aufzuteilen. Sprich eine Story für die Navigation inkl. der Begrüßung des Nutzers und eine Story das Formular. Die Story wirkt recht groß. Aber das kannst du natürlich entscheiden :) vielleicht kannst du auch noch beschreiben was beim Navigationsklick passiert. Sprich: Die Farbe ändert sich, die URL ändert sich...
> 
> Der Punkt was mit den Daten nach dem Absenden passiert müsste auch noch beschrieben werden. Also werden die Daten darunter angezeigt oder ein neuer Eintrag generiert?

Hey Philip, super herzlichen Dank für's reviewen. Ich hab deine Änderungen berücksichtigt, möchte meine User Story aber so lassen. Werde es aber in Zukunft berücksichtigen.  : )
