### ISSUE TITLE
04-US / 04-Calendar / feature/calendar

### ISSUE THREAD

**Issue by Hirnstromwelle** [Hirnstromwelle/userStories#5]
## Value Proposition

**As a** User.

**I need** a overview of my Tasks.

**to be able to** see visually when it's my turn to clean.

## Description

<img width="299" alt="Screenshot 2023-01-04 at 13 00 33" src="https://user-images.githubusercontent.com/63350892/210550736-0e87d8f1-d6d1-43a9-ba15-eebd0eadf5d8.png">

## Acceptance Criteria

- [x] see calendar
- [x] show dates in green color

## Tasks

(for developers team)

- [x] import react calendar component
- [x] expand navigation bar component
- [x] create styles
- [x] Customize the react calendar to my project

**Comment by ufelgen** [comment]
Hey Alex, 

an manchen Stellen würde ich noch spezifizieren: 
show dates in green color - welche Dates? ich nehme an, da wo ein Putzen ansteht?
Customize the react calendar to my project - wie? also was soll der Kalender können?

Viel Erfolg! ich glaub das wird total cool :)
