### ISSUE TITLE
06-US / 06-Appointments / delete and edit button

### ISSUE THREAD

**Issue by Hirnstromwelle** [Hirnstromwelle/userStories#6]
## Value Proposition

**As a** user

**I want to** be able to delete and edit my Appointments

**to be able to** correct or delete my mistakes

## Description

A remove and edit icon, at the right upper edge of the tile. Clickable for the user.

## Acceptance Criteria

- [x] Appointments are edit- and delektable 
- [x] old information stays in field, but can be actively deleted

## Tasks

(for developers team)

- [x] new branch: feature/edit.function
- [x] implement logic for whole table
- [x] either install React extension or choose other way to make all info editable

**Comment by NeeleWaehnke** [comment]
sieht gut aus :)
