### ISSUE TITLE
07-US / Backend / add a database

### ISSUE THREAD

**Issue by Hirnstromwelle** [Hirnstromwelle/userStories#7]
## Value Proposition

**As a developer

**I need** save the data in a database

**to be able to** store it and edit it

## Description

I fully integrate a MongoDB to replace my Array saved in the data lib.

## Acceptance Criteria

- [x] This is a backend task

## Tasks

(for developers team)

- [x] setup a new mongoDB in Atlas
- [x] setup the Atlas connection to the cloud
- [x] write a local .env.local file - that will be added to the .gitignore
